[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["io-util", "time"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
rcgen = "0.14.10"
rustls = { version = "0.23.45", default-features = false, features = ["ring", "std", "tls12", "logging"] }
pem = "4.0.0"
rustls-pki-types = "1.15.1"
ring = "0.17.14"

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1", features = ["rt", "macros"] }
