[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
fuse-fs = { path = "../fuse-fs" }
fuser = "0.18"
tokio-serial = "5"
tokio = { version = "1", features = [
    "io-util",
    "time",
    "rt-multi-thread",
    "net",
    "signal",
    "macros",
] }
rustls = { version = "0.23.45", default-features = false, features = ["ring", "std", "tls12", "logging"] }
tokio-rustls = { version = "0.26.5", default-features = false, features = ["ring", "tls12", "logging"] }
rustls-webpki = "0.103.15"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
